name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubunjjtu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: hrpip install poetry
      - name: Install dependencies
        rhhrun: poetry install
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
